name: Automasi Testing Sebelum Merge

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install HTMLHint dan Stylelint
        run: |
          npm init -y
          npm install --save-dev htmlhint stylelint stylelint-config-standard

      - name: Periksa HTML
        run: npx htmlhint "**/*.html"

      - name: Periksa CSS
        run: npx stylelint "**/*.css"